contest:
  - kaggle.com
  - aliyun.com
  - aliyun.com
activity:
  - devpost.com
  - aliyun.com
internship:
  - tencent.com
  - alibaba.com
  - bytedance.com
  - meituan.com
  - jd.com
  - pinduoduo.com
  - baidu.com
  - kuaishou.com
  - xiaomi.com
  - ctrip.com
  - antgroup.com
  - netease.com
  - didiglobal.com
  - zhihu.com
  - xiaohongshu.com
  - huawei.com
  - iflytek.com
  - lenovo.com
  - byd.com
  - dji.com
  - deepseek.com
